# Generated by Django 5.2.8 on 2025-11-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='aprobado',
        ),
    ]
